# Generated by Django 3.0.2 on 2020-02-14 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0002_remove_warden_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('Subject', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=500)),
                ('file', models.FileField(blank=True, upload_to='notice_files')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciever', to=settings.AUTH_USER_MODEL)),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
